cmake_minimum_required(VERSION 3.15)
project(ASM-Template ASM)

set(CMAKE_EXPORT_COMPILE_COMMANDS ON)

find_program(ASM_COMPILER NAMES ${CMAKE_ASM_COMPILER})
find_program(ASM_LINKER NAMES ${CMAKE_ASM_LINKER})

file(GLOB SOURCES "*.asm")

set(CMAKE_ASM_COMPILE_OBJECT "${ASM_COMPILER} <DEFINES> <INCLUDES> <FLAGS> -o <OBJECT> <SOURCE>")
set(CMAKE_ASM_LINK_EXECUTABLE "${ASM_LINKER} <CMAKE_ASM_LINK_FLAGS> <LINK_FLAGS> <OBJECTS> -o <TARGET> <LINK_LIBRARIES>")

message(STATUS "COMPILING WITH: ${CMAKE_ASM_COMPILE_OBJECT}")
message(STATUS "LINKING WITH: ${CMAKE_ASM_LINK_EXECUTABLE}")

set(CMAKE_ASM_FLAGS -felf64)

add_executable(${PROJECT_NAME} ${SOURCES})
