set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED TRUE)

set(PROJECT_MANAGER_APPLICATION_NAME ${CMAKE_PROJECT_NAME})
set(PROJECT_MANAGER_MAJOR_VERSION ${CMAKE_PROJECT_VERSION_MAJOR})
set(PROJECT_MANAGER_MINOR_VERSION ${CMAKE_PROJECT_VERSION_MINOR})
set(PROJECT_MANAGER_PATCH_VERSION ${CMAKE_PROJECT_VERSION_PATCH})

if(${CMAKE_BUILD_TYPE} STREQUAL "Debug")
  set(PROJECT_MANAGER_DATA_DIR ${CMAKE_CURRENT_BINARY_DIR}/templates)
else()
  set(PROJECT_MANAGER_DATA_DIR ${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_DATADIR}/${PROJECT_MANAGER_APPLICATION_NAME})
endif()

file(GLOB SOURCES "*.cpp")
add_executable(${PROJECT_MANAGER_APPLICATION_NAME} ${SOURCES})

include(GNUInstallDirs)
target_compile_definitions(${PROJECT_MANAGER_APPLICATION_NAME} PRIVATE 
  -DPROJECT_MANAGER_APPLICATION_NAME="${PROJECT_MANAGER_APPLICATION_NAME}"
  -DPROJECT_MANAGER_MAJOR_VERSION=${PROJECT_MANAGER_MAJOR_VERSION}
  -DPROJECT_MANAGER_MINOR_VERSION=${PROJECT_MANAGER_MINOR_VERSION}
  -DPROJECT_MANAGER_PATCH_VERSION=${PROJECT_MANAGER_PATCH_VERSION}
  -DPROJECT_MANAGER_DATA_DIR="${PROJECT_MANAGER_DATA_DIR}"
)

target_include_directories(${PROJECT_MANAGER_APPLICATION_NAME} PRIVATE ${CMAKE_CURRENT_SOURCE_DIR}/../../include/)
target_link_libraries(${PROJECT_MANAGER_APPLICATION_NAME} PRIVATE GArgs)

install(TARGETS ${PROJECT_MANAGER_APPLICATION_NAME})

file(GLOB TEMPLATES "../../templates/*")
foreach(TEMPLATE ${TEMPLATES})
  if(IS_DIRECTORY ${TEMPLATE})
    cmake_path(GET TEMPLATE FILENAME TEMPLATE_NAME)

    # Deprecated
    # if(WIN32)
    #   file(TO_CMAKE_PATH $ENV{HOMEDRIVE}$ENV{HOMEPATH}/${APPLICATION_NAME} INSTALL_PATH)
    #   install(DIRECTORY ${TEMPLATE} DESTINATION ${INSTALL_PATH})
    #   message(STATUS "Template install location: ${INSTALL_PATH}")
    # else()
    #   install(DIRECTORY ${TEMPLATE} DESTINATION $ENV{HOME}/ProjectManager/)
    #   message(STATUS "Template install location: $ENV{HOME}/ProjectManager/")
    # endif()

    message(STATUS "Adding template: ${TEMPLATE}")
    install(DIRECTORY ${TEMPLATE} DESTINATION ${CMAKE_INSTALL_DATADIR}/${PROJECT_MANAGER_APPLICATION_NAME})

    make_directory("${CMAKE_CURRENT_BINARY_DIR}/templates/${TEMPLATE_NAME}")
    add_custom_command(TARGET ${PROJECT_MANAGER_APPLICATION_NAME} POST_BUILD
                   COMMAND ${CMAKE_COMMAND} -E copy_directory
                   ${TEMPLATE} "${PROJECT_MANAGER_DATA_DIR}/${TEMPLATE_NAME}")
  endif()
endforeach()
